= Model Serving
include::_attributes.adoc[]

. At this point, we need to deploy the model into RHOAI model serving.
. For this, we have prepared a data connection that points to the `object-detection` bucket, which contains the fully retrained accident detection model.

== Deploy the model

In order to deploy the accident detection model, we can follow similar steps as before:

* In the bottom section (Models and model servers), select `Deploy model`.
* In the model deployment form, enter the following details:
** Model name: `accident-detection`
** Serving runtime: `OpenVINO Model Server`
** Model framework: `onnx`
** Number of model server replicas: 1
** Model server size: `Standard`
** Accelerator: `None`
** Select `Existing data connection` with
*** name `object-detection` and
*** path `models/accident-detection`.
* Hit `Deploy`.

Once the model's status is green, we will confirm that the model is indeed working by querying it!

== Querying the served Model

Once the model is served, we can use it as an endpoint that can be queried. We'll send a request to it, and get a result. And unlike our earlier notebook-based version, this applies to anyone working within our cluster. This could either be colleagues, or applications.

* First, we need to get the URL of the model server.
* Note or copy the **Inference endpoint**.

We will now use this URL to query the model.

- In your running workbench, navigate to the folder `insurance-claim-processing/lab-materials/04`.
- Look for (and open) the notebook called `04-05-model-serving.ipynb`.
- Execute the cells of the notebook, and ensure you understand what is happening.

